name: Lighthouse Scan Automation

on:
  workflow_dispatch: # Déclencheur manuel
  push:              # Déclenche aussi à chaque push sur main
    branches:
      - main
  pull_request:      # Et aussi sur PR vers main
    branches:
      - main

jobs:
  lighthouse-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set script permissions
        run: chmod +x ./lighthouse-scan-command-lines.sh

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Lighthouse globally
        run: npm install -g lighthouse

      - name: Run Lighthouse scans
        run: ./lighthouse-scan-command-lines.sh

      - name: Upload Lighthouse Reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            Reports/*.html
            Reports/*.json
            Reports/*.csv

      - name: Display Lighthouse Scores in logs
        run: |
          echo "Extraction des scores Lighthouse :"
          for file in Reports/*.json; do
            echo "----"
            echo "Fichier : $file"
            performance=$(jq '.categories.performance.score' "$file")
            accessibility=$(jq '.categories.accessibility.score' "$file")
            bestPractices=$(jq '.categories["best-practices"].score' "$file")
            seo=$(jq '.categories.seo.score' "$file")
            echo "Performance Score    : $performance"
            echo "Accessibility Score  : $accessibility"
            echo "Best Practices Score : $bestPractices"
            echo "SEO Score            : $seo"
          done
