name: Lighthouse Scan Automation

on:
  workflow_dispatch: # Déclencheur manuel
  push:              # Déclenche aussi à chaque push sur main
    branches:
      - main
  pull_request:      # Et aussi sur PR vers main
    branches:
      - main

jobs:
  lighthouse-scan:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris  # ➕ Active la timezone Europe/Paris pour tout le job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set script permissions
        run: chmod +x ./lighthouse-scan-command-lines.sh

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Lighthouse globally
        run: npm install -g lighthouse

      - name: Clean Reports directory
        run: |
          rm -rf Reports/*
          mkdir -p Reports

      - name: Run Lighthouse scans
        run: ./lighthouse-scan-command-lines.sh json,html accessibility,seo,best-practices

      - name: Upload Lighthouse Reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            Reports/*.html
            Reports/*.json
            Reports/*.csv

      - name: Display Lighthouse Scores in logs
        run: |
          echo "Extraction des scores Lighthouse :"
          for file in Reports/*.json; do
            echo "----"
            echo "Fichier : $file"
            performance=$(jq '.categories.performance.score' "$file")
            accessibility=$(jq '.categories.accessibility.score' "$file")
            bestPractices=$(jq '.categories["best-practices"].score' "$file")
            seo=$(jq '.categories.seo.score' "$file")
            echo "Performance Score    : $performance"
            echo "Accessibility Score  : $accessibility"
            echo "Best Practices Score : $bestPractices"
            echo "SEO Score            : $seo"
          done

      - name: Append results to CSV
        run: |
          now=$(date +"%Y-%m-%dT%H:%M:%S+02:00")
          for file in Reports/*.json; do
            url=$(jq -r '.finalUrl' "$file")
            perf=$(jq '.categories.performance.score' "$file")
            acc=$(jq '.categories.accessibility.score' "$file")
            best=$(jq '.categories["best-practices"].score' "$file")
            seo=$(jq '.categories.seo.score' "$file")
            echo "$now,$url,$perf,$acc,$best,$seo" >> lighthouse-history.csv
          done

      - name: Commit and push history file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add lighthouse-history.csv
          git commit -m "📊 Update Lighthouse score history [skip ci]" || echo "No changes to commit"
          git push

      - name: Confirm push
        run: echo "✅ CSV historisé et poussé avec succès !"
